// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  String firebase_message_token = 'AAAAroemubE:APA91bH_-j0J5H5ADNnEOGLYRpPnMjt5xni5ZLCEef6JjRqKY_sGuRC3Qkfl3UuKpp_2lL3XGKUh6NzMSjBcoIRE1Qmv_pLvUDFl9L2wB3DcjreOmP8JdueV7Q11bshp2D8qPnM7eDRe';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSlFScm33QgC8L2a3fVfHam4l4cTaJlo',
    appId: '1:749600160177:web:1320d8df961336b5776590',
    messagingSenderId: '749600160177',
    projectId: 'fridgeit-d17ae',
    authDomain: 'fridgeit-d17ae.firebaseapp.com',
    databaseURL: 'https://fridgeit-d17ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgeit-d17ae.appspot.com',
    measurementId: 'G-V0F5B5DH5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFSm_WxEHXsNYXAOs_AQsVFMgR9O-WwU',
    appId: '1:749600160177:android:0a8f4553e301bf58776590',
    messagingSenderId: '749600160177',
    projectId: 'fridgeit-d17ae',
    databaseURL: 'https://fridgeit-d17ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgeit-d17ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtvpxiwJzy0mdIBD9LVpsqUrbzJBPLwE',
    appId: '1:749600160177:ios:31b96349fcfabccc776590',
    messagingSenderId: '749600160177',
    projectId: 'fridgeit-d17ae',
    databaseURL: 'https://fridgeit-d17ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgeit-d17ae.appspot.com',
    iosClientId: '749600160177-hskivr7lt8skftqg0hniu43vjiavmr8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.babeIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtvpxiwJzy0mdIBD9LVpsqUrbzJBPLwE',
    appId: '1:749600160177:ios:31b96349fcfabccc776590',
    messagingSenderId: '749600160177',
    projectId: 'fridgeit-d17ae',
    databaseURL: 'https://fridgeit-d17ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgeit-d17ae.appspot.com',
    iosClientId: '749600160177-hskivr7lt8skftqg0hniu43vjiavmr8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.babeIt',
  );
}
